version: "3.4"
services:
  app:
    build:
      context: .
      target: builder
    entrypoint:
      - tail
    command:
      - -f
      - /dev/null
    ports:
      - 3006:3006
    volumes:
      - .:/app
      - /app/node_modules
