// Authentication Actions
export const LOGIN = "LOGIN";
export const COOKIE_AUTH = "COOKIE_AUTH";

// Rider Actions
export const SET_FILTER = "SET_FILTER";
export const FETCH_RIDE_FEED = "FETCH_RIDE_FEED";
export const FETCH_MORE_RIDE_FEED = "FETCH_MORE_RIDE_FEED";
export const FETCH_UPCOMING_RIDE = "FETCH_UPCOMING_RIDE";
export const INCREMENT_RIDER_NUM = "INCREMENT_RIDER_NUM";

// Driver Actions
export const FETCH_DRIVE_HISTORY = "FETCH_DRIVE_HISTORY";
export const FETCH_MORE_DRIVE_HISTORY = "FETCH_MORE_DRIVE_HISTORY";
export const FETCH_UPCOMING_DRIVE = "FETCH_UPCOMING_DRIVE";
export const INCREMENT_DRIVER_NUM = "INCREMENT_DRIVER_NUM";

// Toggle Modals
export const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";
export const TOGGLE_INFO_MODAL = "TOGGLE_INFO_MODAL";

// Handle Notifications
export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
